cmake_minimum_required(VERSION 3.18)

if(NOT DEFINED WC_DIR OR WC_DIR STREQUAL "")
    message(FATAL_ERROR "WC_DIR must point to the Wallet Core source tree")
endif()

file(REAL_PATH "${WC_DIR}" WC_DIR)
set(REGISTRY "${WC_DIR}/registry.json")
if(NOT EXISTS "${REGISTRY}")
    message(FATAL_ERROR "Wallet Core registry.json is missing: ${REGISTRY}")
endif()

file(READ "${REGISTRY}" REGISTRY_JSON)
string(JSON COIN_COUNT LENGTH "${REGISTRY_JSON}")
if(COIN_COUNT LESS 1)
    message(FATAL_ERROR "Wallet Core registry.json contains no coins")
endif()

function(json_optional OBJECT KEY DEFAULT_VALUE OUT_VAR)
    string(JSON _value ERROR_VARIABLE _err GET "${OBJECT}" "${KEY}")
    if(NOT _err STREQUAL "NOTFOUND")
        set(_value "${DEFAULT_VALUE}")
    endif()
    set(${OUT_VAR} "${_value}" PARENT_SCOPE)
endfunction()

function(json_has OBJECT KEY OUT_VAR)
    string(JSON _type ERROR_VARIABLE _err TYPE "${OBJECT}" "${KEY}")
    if(_err STREQUAL "NOTFOUND")
        set(${OUT_VAR} TRUE PARENT_SCOPE)
    else()
        set(${OUT_VAR} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(format_name INPUT OUT_VAR)
    set(_value "${INPUT}")
    string(REGEX MATCH "^[a-z]+" _prefix "${_value}")
    if(NOT _prefix STREQUAL "")
        string(TOUPPER "${_prefix}" _upper)
        string(LENGTH "${_prefix}" _prefix_len)
        string(SUBSTRING "${_value}" ${_prefix_len} -1 _rest)
        set(_value "${_upper}${_rest}")
    endif()
    string(REGEX REPLACE "[-.]" " " _value "${_value}")
    string(REGEX REPLACE "[ \t\r\n]+" "" _value "${_value}")
    set(${OUT_VAR} "${_value}" PARENT_SCOPE)
endfunction()

function(camel_case INPUT OUT_VAR)
    string(LENGTH "${INPUT}" _len)
    if(_len EQUAL 0)
        set(${OUT_VAR} "" PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${INPUT}" 0 1 _first)
    string(TOUPPER "${_first}" _first)
    if(_len GREATER 1)
        string(SUBSTRING "${INPUT}" 1 -1 _rest)
        string(TOLOWER "${_rest}" _rest)
    else()
        set(_rest "")
    endif()
    set(${OUT_VAR} "${_first}${_rest}" PARENT_SCOPE)
endfunction()

function(cpp_escape INPUT OUT_VAR)
    set(_value "${INPUT}")
    string(REPLACE "\\" "\\\\" _value "${_value}")
    string(REPLACE "\"" "\\\"" _value "${_value}")
    string(REPLACE "\n" "\\n" _value "${_value}")
    string(REPLACE "\r" "" _value "${_value}")
    set(${OUT_VAR} "${_value}" PARENT_SCOPE)
endfunction()

function(derivation_enum_name DERIV COIN OUT_VAR)
    json_has("${DERIV}" "name" _has_name)
    if(NOT _has_name)
        set(${OUT_VAR} "TWDerivationDefault" PARENT_SCOPE)
        return()
    endif()
    string(JSON _deriv_name GET "${DERIV}" name)
    string(JSON _coin_name GET "${COIN}" name)
    format_name("${_coin_name}" _coin_fmt)
    camel_case("${_deriv_name}" _deriv_fmt)
    set(${OUT_VAR} "TWDerivation${_coin_fmt}${_deriv_fmt}" PARENT_SCOPE)
endfunction()

# Preserve upstream ordering: registry entries sorted by numeric coinId.
set(COIN_KEYS "")
math(EXPR LAST_COIN "${COIN_COUNT} - 1")
foreach(I RANGE 0 ${LAST_COIN})
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    string(JSON COIN_ID GET "${COIN}" coinId)
    list(APPEND COIN_KEYS "${COIN_ID}:${I}")
endforeach()
list(SORT COIN_KEYS COMPARE NATURAL ORDER ASCENDING)

set(GENERATED_NOTICE "// SPDX-License-Identifier: Apache-2.0\n//\n// Copyright © 2017 Trust Wallet.\n//\n// This is a GENERATED FILE from \\registry.json, changes made here WILL BE LOST.\n//\n")

# ---- TWDerivation.h ---------------------------------------------------------
set(OUT "${GENERATED_NOTICE}\n#pragma once\n\n#include \"TWBase.h\"\n\nTW_EXTERN_C_BEGIN\n\n/// Non-default coin address derivation names (default, unnamed derivations are not included).\nTW_EXPORT_ENUM()\nenum TWDerivation {\n    TWDerivationDefault = 0, // default, for any coin\n    TWDerivationCustom = 1, // custom, for any coin\n")
set(ENUM_COUNT 1)
foreach(KEY IN LISTS COIN_KEYS)
    string(REGEX REPLACE "^[0-9]+:" "" I "${KEY}")
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    string(JSON DERIV_COUNT LENGTH "${COIN}" derivation)
    if(DERIV_COUNT GREATER 1)
        math(EXPR LAST_DERIV "${DERIV_COUNT} - 1")
        foreach(D RANGE 0 ${LAST_DERIV})
            string(JSON DERIV GET "${COIN}" derivation ${D})
            json_has("${DERIV}" "name" HAS_NAME)
            if(D GREATER 0 OR HAS_NAME)
                derivation_enum_name("${DERIV}" "${COIN}" ENUM_NAME)
                math(EXPR ENUM_COUNT "${ENUM_COUNT} + 1")
                string(APPEND OUT "    ${ENUM_NAME} = ${ENUM_COUNT},\n")
            endif()
        endforeach()
    endif()
endforeach()
string(APPEND OUT "};\n\nTW_EXTERN_C_END\n")
file(WRITE "${WC_DIR}/include/TrustWalletCore/TWDerivation.h" "${OUT}")

# ---- TWHRP.h / TWHRP.cpp ---------------------------------------------------
set(HRP_HEADER "${GENERATED_NOTICE}\n#pragma once\n\n#include \"TWBase.h\"\n\nTW_EXTERN_C_BEGIN\n\n///  Registered human-readable parts for BIP-0173\n///\n/// - SeeAlso: https://github.com/satoshilabs/slips/blob/master/slip-0173.md\nTW_EXPORT_ENUM()\nenum TWHRP {\n    TWHRPUnknown     /* \"\" */,\n")
set(HRP_CPP "${GENERATED_NOTICE}\n#include <TrustWalletCore/TWHRP.h>\n\n#include <cstring>\n\nconst char* stringForHRP(enum TWHRP hrp) {\n    switch (hrp) {\n")
set(HRP_COINS "")
foreach(KEY IN LISTS COIN_KEYS)
    string(REGEX REPLACE "^[0-9]+:" "" I "${KEY}")
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    json_has("${COIN}" "hrp" HAS_HRP)
    if(HAS_HRP)
        list(APPEND HRP_COINS "${I}")
        string(JSON NAME GET "${COIN}" name)
        format_name("${NAME}" NAME_FMT)
        string(JSON HRP GET "${COIN}" hrp)
        string(APPEND HRP_HEADER "    TWHRP${NAME_FMT}     /* \"${HRP}\" */,\n")
        string(JSON ID GET "${COIN}" id)
        string(TOUPPER "${ID}" ID_UPPER)
        string(APPEND HRP_CPP "    case TWHRP${NAME_FMT}:\n        return HRP_${ID_UPPER};\n")
    endif()
endforeach()
string(APPEND HRP_HEADER "};\n\n")
foreach(I IN LISTS HRP_COINS)
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    string(JSON ID GET "${COIN}" id)
    string(TOUPPER "${ID}" ID_UPPER)
    string(JSON HRP GET "${COIN}" hrp)
    cpp_escape("${HRP}" HRP_ESC)
    string(APPEND HRP_HEADER "static const char *_Nonnull HRP_${ID_UPPER} = \"${HRP_ESC}\";\n")
endforeach()
string(APPEND HRP_HEADER "\nconst char *_Nullable stringForHRP(enum TWHRP hrp);\nenum TWHRP hrpForString(const char *_Nonnull string);\n\nTW_EXTERN_C_END\n")
string(APPEND HRP_CPP "    default: return nullptr;\n    }\n}\n\nenum TWHRP hrpForString(const char *_Nonnull string) {\n")
set(FIRST TRUE)
foreach(I IN LISTS HRP_COINS)
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    string(JSON NAME GET "${COIN}" name)
    format_name("${NAME}" NAME_FMT)
    string(JSON ID GET "${COIN}" id)
    string(TOUPPER "${ID}" ID_UPPER)
    if(FIRST)
        string(APPEND HRP_CPP "    if (std::strcmp(string, HRP_${ID_UPPER}) == 0) {\n")
        set(FIRST FALSE)
    else()
        string(APPEND HRP_CPP "    } else if (std::strcmp(string, HRP_${ID_UPPER}) == 0) {\n")
    endif()
    string(APPEND HRP_CPP "        return TWHRP${NAME_FMT};\n")
endforeach()
string(APPEND HRP_CPP "    } else {\n        return TWHRPUnknown;\n    }\n}\n")
file(MAKE_DIRECTORY "${WC_DIR}/src/Generated")
file(WRITE "${WC_DIR}/include/TrustWalletCore/TWHRP.h" "${HRP_HEADER}")
file(WRITE "${WC_DIR}/src/Generated/TWHRP.cpp" "${HRP_CPP}")

# ---- TWEthereumChainID.h ----------------------------------------------------
set(CHAIN_HEADER "${GENERATED_NOTICE}\n#pragma once\n\n#include \"TWBase.h\"\n\nTW_EXTERN_C_BEGIN\n\n/// Chain identifiers for Ethereum-based blockchains, for convenience. Recommended to use the dynamic CoinType.ChainId() instead.\n/// See also TWChainId.\nTW_EXPORT_ENUM(uint32_t)\nenum TWEthereumChainID {\n")
foreach(KEY IN LISTS COIN_KEYS)
    string(REGEX REPLACE "^[0-9]+:" "" I "${KEY}")
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    string(JSON BLOCKCHAIN GET "${COIN}" blockchain)
    if(BLOCKCHAIN STREQUAL "Ethereum" OR BLOCKCHAIN STREQUAL "Ronin" OR BLOCKCHAIN STREQUAL "Vechain")
        json_optional("${COIN}" "deprecated" "OFF" DEPRECATED)
        if(NOT DEPRECATED)
            string(JSON ID GET "${COIN}" id)
            camel_case("${ID}" ID_FMT)
            json_optional("${COIN}" "chainId" "" CHAIN_ID)
            string(APPEND CHAIN_HEADER "    TWEthereumChainID${ID_FMT} = ${CHAIN_ID},\n")
        endif()
    endif()
endforeach()
string(APPEND CHAIN_HEADER "};\n\nTW_EXTERN_C_END\n")
file(WRITE "${WC_DIR}/include/TrustWalletCore/TWEthereumChainID.h" "${CHAIN_HEADER}")

# ---- CoinInfoData.cpp -------------------------------------------------------
set(COIN_CPP "// SPDX-License-Identifier: Apache-2.0\n//\n// Copyright © 2017 Trust Wallet.\n//\n// This is a GENERATED FILE, changes made here WILL BE LOST.\n//\n\n#include \"Coin.h\"\n#include <TrustWalletCore/TWCoinTypeConfiguration.h>\n\n#include <vector>\n#include <cassert>\n\nusing namespace TW;\n\nstatic const CoinInfo defaultsForMissing = {\n    \"?\",\n    \"?\",\n    TWBlockchainBitcoin,\n    TWPurposeBIP44,\n    TWCurveNone,\n    {Derivation()},\n    TWPublicKeyTypeSECP256k1,\n    0,\n    0,\n    0,\n    TWHRPUnknown,\n    \"\",\n    Hash::HasherSha256ripemd,\n    Hash::HasherSha256d,\n    Hash::HasherSha256ripemd,\n    \"?\",\n    2,\n    \"\",\n    \"\",\n    0,\n    0\n};\n\n/// Get coin from map, if missing returns defaults (not to have contains-check in each accessor method)\nconst CoinInfo getCoinInfo(TWCoinType coin) {\n    // switch is preferred instead of a data structure, due to initialization issues\n    switch (coin) {\n")
set(COIN_TYPE_LINES "")
foreach(KEY IN LISTS COIN_KEYS)
    string(REGEX REPLACE "^[0-9]+:" "" I "${KEY}")
    string(JSON COIN GET "${REGISTRY_JSON}" ${I})
    string(JSON NAME GET "${COIN}" name)
    format_name("${NAME}" NAME_FMT)
    string(JSON ID GET "${COIN}" id)
    json_optional("${COIN}" "displayName" "${NAME}" DISPLAY_NAME)
    string(JSON BLOCKCHAIN GET "${COIN}" blockchain)
    format_name("${BLOCKCHAIN}" BLOCKCHAIN_FMT)
    string(JSON CURVE GET "${COIN}" curve)
    format_name("${CURVE}" CURVE_FMT)
    string(JSON PUBTYPE GET "${COIN}" publicKeyType)
    format_name("${PUBTYPE}" PUBTYPE_FMT)
    string(JSON DERIV_COUNT LENGTH "${COIN}" derivation)
    string(JSON FIRST_PATH GET "${COIN}" derivation 0 path)
    string(REGEX MATCH "^m/([0-9]+)" _purpose_match "${FIRST_PATH}")
    if(CMAKE_MATCH_1 STREQUAL "")
        message(FATAL_ERROR "Unable to determine BIP purpose for ${NAME}: ${FIRST_PATH}")
    endif()
    set(PURPOSE "${CMAKE_MATCH_1}")

    cpp_escape("${ID}" ID_ESC)
    cpp_escape("${DISPLAY_NAME}" DISPLAY_ESC)
    string(APPEND COIN_CPP "        case TWCoinType${NAME_FMT}:\n            return CoinInfo {\n                \"${ID_ESC}\",\n                \"${DISPLAY_ESC}\",\n                TWBlockchain${BLOCKCHAIN_FMT},\n                TWPurposeBIP${PURPOSE},\n                TWCurve${CURVE_FMT},\n                {\n")
    math(EXPR LAST_DERIV "${DERIV_COUNT} - 1")
    foreach(D RANGE 0 ${LAST_DERIV})
        string(JSON DERIV GET "${COIN}" derivation ${D})
        derivation_enum_name("${DERIV}" "${COIN}" DERIV_ENUM)
        string(JSON PATH GET "${DERIV}" path)
        cpp_escape("${PATH}" PATH_ESC)
        json_optional("${DERIV}" "name" "" DERIV_NAME)
        string(TOLOWER "${DERIV_NAME}" DERIV_NAME)
        cpp_escape("${DERIV_NAME}" DERIV_NAME_ESC)
        json_optional("${DERIV}" "xpub" "" XPUB)
        if(XPUB STREQUAL "")
            set(XPUB_ENUM "None")
        else()
            format_name("${XPUB}" XPUB_ENUM)
        endif()
        json_optional("${DERIV}" "xprv" "" XPRV)
        if(XPRV STREQUAL "")
            set(XPRV_ENUM "None")
        else()
            format_name("${XPRV}" XPRV_ENUM)
        endif()
        string(APPEND COIN_CPP "                    {\n                        ${DERIV_ENUM},\n                        \"${PATH_ESC}\",\n                        \"${DERIV_NAME_ESC}\",\n                        TWHDVersion${XPUB_ENUM},\n                        TWHDVersion${XPRV_ENUM},\n                    },\n")
    endforeach()
    string(APPEND COIN_CPP "                },\n                TWPublicKeyType${PUBTYPE_FMT},\n")

    json_optional("${COIN}" "staticPrefix" "0" STATIC_PREFIX)
    json_optional("${COIN}" "p2pkhPrefix" "0" P2PKH_PREFIX)
    json_optional("${COIN}" "p2shPrefix" "0" P2SH_PREFIX)
    json_has("${COIN}" "hrp" HAS_HRP)
    if(HAS_HRP)
        set(HRP_ENUM "${NAME_FMT}")
    else()
        set(HRP_ENUM "Unknown")
    endif()
    json_optional("${COIN}" "chainId" "" CHAIN_ID)
    json_optional("${COIN}" "publicKeyHasher" "sha256ripemd" PUBLIC_HASH)
    camel_case("${PUBLIC_HASH}" PUBLIC_HASH_FMT)
    json_optional("${COIN}" "base58Hasher" "sha256d" BASE58_HASH)
    camel_case("${BASE58_HASH}" BASE58_HASH_FMT)
    json_optional("${COIN}" "addressHasher" "sha256ripemd" ADDRESS_HASH)
    camel_case("${ADDRESS_HASH}" ADDRESS_HASH_FMT)
    string(JSON SYMBOL GET "${COIN}" symbol)
    string(JSON DECIMALS GET "${COIN}" decimals)
    json_optional("${COIN}" "slip44" "" SLIP44)
    if(SLIP44 STREQUAL "")
        string(JSON SLIP44 GET "${COIN}" coinId)
    endif()
    json_optional("${COIN}" "ss58Prefix" "0" SS58)
    string(JSON EXPLORER GET "${COIN}" explorer)
    json_optional("${EXPLORER}" "url" "" EXPLORER_URL)
    json_optional("${EXPLORER}" "txPath" "" TX_PATH)
    json_optional("${EXPLORER}" "accountPath" "" ACCOUNT_PATH)
    set(TX_URL "${EXPLORER_URL}${TX_PATH}")
    set(ACCOUNT_URL "${EXPLORER_URL}${ACCOUNT_PATH}")
    cpp_escape("${CHAIN_ID}" CHAIN_ID_ESC)
    cpp_escape("${SYMBOL}" SYMBOL_ESC)
    cpp_escape("${TX_URL}" TX_URL_ESC)
    cpp_escape("${ACCOUNT_URL}" ACCOUNT_URL_ESC)

    string(APPEND COIN_CPP "                ${STATIC_PREFIX},\n                ${P2PKH_PREFIX},\n                ${P2SH_PREFIX},\n                TWHRP${HRP_ENUM},\n                \"${CHAIN_ID_ESC}\",\n                Hash::Hasher${PUBLIC_HASH_FMT},\n                Hash::Hasher${BASE58_HASH_FMT},\n                Hash::Hasher${ADDRESS_HASH_FMT},\n                \"${SYMBOL_ESC}\",\n                ${DECIMALS},\n                \"${TX_URL_ESC}\",\n                \"${ACCOUNT_URL_ESC}\",\n                ${SLIP44},\n                ${SS58},\n            };\n")
    string(APPEND COIN_TYPE_LINES "        TWCoinType${NAME_FMT},\n")
endforeach()
string(APPEND COIN_CPP "        default:\n            return defaultsForMissing;\n    }\n}\n\nstd::vector<TWCoinType> TW::getCoinTypes() {\n    return std::vector<TWCoinType>({\n${COIN_TYPE_LINES}    });\n}\n")
file(WRITE "${WC_DIR}/src/Generated/CoinInfoData.cpp" "${COIN_CPP}")

message(STATUS "Wallet Core registry-derived sources generated from ${REGISTRY}")
